### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by leostera** [warp-build/warp#15]
Hi team, this is a checklist of stuff that we should have in place before announcing the first release. Would love to hear your thoughts and if anything is missing here.

- [x] CD:
   - [x] CI passes for Linux and macOS
   - [x] New releases are created on tags and published to Github Releases
- [ ] Docs:
   - [x] README.md includes basic information about the project (see https://github.com/denoland/deno/blob/main/README.md)
   - [x] `docs.warp.build` is deployed from `main`
   - [x] Installation page shows how to install warp from sources
   - [ ] Concepts page explains our core concepts (Target, Signature, Tricorder, Phases, etc)
   - [ ] CONTRIBUTING.md includes instructions for
      - [x] How to set up the project locally
      - [ ] How to contribute (PR etiquette, commit messages, etc)

Feel free to pick up any of this work, just make an issue for it and go bananas 🚀 

cc/ @capitanu @diogomqbm @Enkronan
